# Generated by Django 5.2.7 on 2025-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('img', models.URLField(max_length=500)),
                ('if_affiliated', models.BooleanField(default=False)),
                ('reviews', models.TextField(blank=True)),
            ],
        ),
    ]
