# Generated by Django 5.2.7 on 2025-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.CharField(default='생활용품', max_length=100),
        ),
    ]
