# Generated by Django 5.2.7 on 2025-10-12 08:24

import pgvector.django.vector
from django.db import migrations, models


def enable_pgvector(apps, schema_editor):
    # PostgreSQL에서만 확장 설치
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_classification'),
    ]

    operations = [
        migrations.RunPython(enable_pgvector, migrations.RunPython.noop),
        migrations.AddField(
            model_name='product',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='shop_produc_categor_01dab4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='shop_produc_brand_ae7a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['if_affiliated'], name='shop_produc_if_affi_485f91_idx'),
        ),
    ]
